### ISSUE TITLE
Lockscreen

### ISSUE THREAD

**Issue by quentinios** [andrewwiik/LittleX#37]
I do not have the lock screen on iPhone X with LittleX 11.0.3 iPhone 7 Plus 
![c233f833-29b3-4297-aaac-7934ccc2a2d2](https://user-images.githubusercontent.com/36057708/35731386-a55a3622-0815-11e8-8a8c-52e7b716f80c.png)

**Comment by imodder** [comment]
me too, ios 11.0.2 it is caused at 11.0.x devices because iphone x come with 11.1.x for that reason 11.0.x older devices not have iphone x's lockscreen ui elements e.g. flashlight, camera, swipe to unlock indicator. iphone x lockscreen ui elements from 11.1.x devices should be ported to 11.0.x devices in some way with littex or another tweak.

**Comment by quentinios** [comment]
so how he can solve the problem I had similar with fluidity ?

**Comment by imodder** [comment]
developers should port needed ui files from 11.1.x firmware to 11.0.1 devices with a tweak...

**Comment by quentinios** [comment]
here is the problem
