### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by beko4398** [andrewwiik/LittleX#78]
When i close something horizontal, the dock reflection become this : ![tfcmokqr](https://user-images.githubusercontent.com/36137714/35781596-317ac642-09fd-11e8-92b3-0a9a6dac7109.jpg)

This game is crashing after 1-3 minutes playing : https://itunes.apple.com/tr/app/online-kafa-topu/id885788690?l=tr

Youtube app has little blank at bottom : ![2018-02-04 22 48 51](https://user-images.githubusercontent.com/36137714/35781620-a37caf9e-09fd-11e8-9044-e16816c5d565.png)

Instagram stories have black space on statusbar : 
![2018-02-04 22 58 08](https://user-images.githubusercontent.com/36137714/35781750-3bb9d0e2-09ff-11e8-976a-ed3e03ff374f.png)

**Comment by andrewwiik** [comment]
The Instagram stories are supposed to have the black bar because that is how it is on the X with the larger status bar, YouTube has a improper implementation safe area insets (I'm assuming you disabled the home bar), just disable LittleX in the app that is crashing, talk to the developer of anemone about the reflection bug as this is not a problem with LittleX
